name: Qodana Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth:

      - name: Check if qodana-results folder exists
        id: check_folder
        run: |
          if [ -d "qodana-results" ]; then
            echo "Qodana results folder exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Qodana results folder does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Assign a dynamic port
        id: assign_port
        run: |
          DEFAULT_PORT=8080
          PORT=${DEFAULT_PORT}
          while lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null; do
            PORT=$((PORT + 1))
          done
          echo "PORT=$PORT" >> $GITHUB_ENV
          echo "Using port: $PORT"

      - name: Set Git Information
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch --unshallow

      - name: Debug Git Information
        run: |
          ls -la .git
          git status
          git branch -a

      - name: Run Qodana if results folder exists
        if: env.exists == 'true'
        run: |
          docker run -e GIT_REPOSITORY="https://github.com/${{ github.repository }}" \
            -e GIT_BRANCH="${{ github.ref }}" \
            -e GIT_COMMIT="${{ github.sha }}" \
            -v $(pwd):/mnt/project \
            jetbrains/qodana:latest \
            --project-dir /mnt/project \
            -o /mnt/project/qodana-results \
            -s -w \
            -p ${{ env.PORT }}:${{ env.PORT }}

      - name: Pull and run Qodana if results folder does not exist
        if: env.exists == 'false'
        run: |
          docker pull jetbrains/qodana:latest
          docker run -e GIT_REPOSITORY="https://github.com/${{ github.repository }}" \
            -e GIT_BRANCH="${{ github.ref }}" \
            -e GIT_COMMIT="${{ github.sha }}" \
            -v $(pwd):/mnt/project \
            -v $(pwd)/qodana-results:/data/results \
            -p ${{ env.PORT }}:${{ env.PORT }} \
            jetbrains/qodana:latest \
            --project-dir /mnt/project \
            -o /data/results \
            -s -w
