name: Qodana Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Qodana
      run: |
        docker pull jetbrains/qodana:latest
        docker run -v $PWD:/mnt/project \
          -v $PWD/qodana-results:/data/results \
          -p 8080:8080 \
          jetbrains/qodana:latest --project-dir /mnt/project -o /data/results -s -w
