name: Qodana Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if qodana-results folder exists
        id: check_folder
        run: |
          if [ -d "qodana-results" ]; then
            echo "Qodana results folder exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Qodana results folder does not exist."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Run Qodana if results folder exists
        if: env.exists == 'true'
        run: |
          docker run -v $(pwd):/mnt/project jetbrains/qodana:latest --project-dir /mnt/project -o /mnt/project/qodana-results -s -w

      - name: Pull and run Qodana if results folder does not exist
        if: env.exists == 'false'
        run: |
          docker pull jetbrains/qodana:latest
          docker run -v $(pwd):/mnt/project -v $(pwd)/qodana-results:/data/results -p 8080:8080 jetbrains/qodana:latest --project-dir /mnt/project -o /data/results -s -w
